
server:
  port: 18051

# Try to launch unit-tests with Embedded MongoDB with 3.6.3 runtime.. - no luck (try uncomment flapdoodle in pom.xml)
spring:
  mongodb:
    embedded:
      version: 3.6.3
      features: ONLY_WITH_SSL,ONLY_WINDOWS_2008_SERVER,ONLY_64BIT,SYNC_DELAY,NO_HTTP_INTERFACE_ARG
      
  data:
    mongodb:
      host: localhost      
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18091/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    orgstruct:
      enabled: true

